Add Traditional Chinese translation (zh-tr)
RTa-technology/ftml-web pull request #127
Opened 2023-06-19 14:56 UTC by PaoMian0806

2023-06-22 02:36 UTC, RTa-technology commented
I will check today or tomorrow ...
If you don't get a response, please send me a @mention.

2023-06-23 09:56 UTC, RTa-technology commented
please ,rename it from `message.yaml` to `messages.yaml`.

2023-06-23 09:57 UTC, RTa-technology requested changes

2023-06-23 09:57 UTC, RTa-technology commented on src/public/locales/zh-tr/top.ftml
> +[[li]][[[contact-staff |聯絡工作人員]]][[ul]]
```
	[[li]][[[contact-staff |聯絡工作人員]]][[/li]][[/ul]]
```

2023-06-23 09:57 UTC, RTa-technology commented on src/public/locales/zh-tr/top.ftml
> +[[li]][[[contact-staff |聯絡工作人員]]][[ul]]
```
	[[li]][[[contact-staff |聯絡工作人員]]][[/li]][[/ul]]
```

2023-06-23 09:57 UTC, RTa-technology commented on src/public/locales/zh-tr/message.yaml
please ,rename it from `message.yaml` to `messages.yaml`.

2023-06-23 10:04 UTC, RTa-technology commented
@PaoMian0806 pls recheck

2023-06-23 16:17 UTC, PaoMian0806 commented
Done👍

2023-06-24 18:49 UTC, RTa-technology approved these changes

2023-06-24 18:49 UTC, merged